// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { getAppConfig, useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { useState, useCallback, useMemo, useEffect, useRef, useContext, useReducer } from 'react';
  export { fakeBrowser } from 'wxt/testing';
  export { ApiDocGenerator } from '../components/ApiDocGenerator';
  export { CaptureFilter } from '../components/CaptureFilter';
  export { CertificateViewer } from '../components/CertificateViewer';
  export { CollectionRunner } from '../components/CollectionRunner';
  export { CollectionsView } from '../components/CollectionsView';
  export { CookieManager } from '../components/CookieManager';
  export { DiagnosticsPanel } from '../components/DiagnosticsPanel';
  export { EnvironmentManager } from '../components/EnvironmentManager';
  export { ExportPanel } from '../components/ExportPanel';
  export { GitHubSyncPanel } from '../components/GitHubSyncPanel';
  export { ImportModal } from '../components/ImportModal';
  export { MockServerManager } from '../components/MockServerManager';
  export { ProfileManager } from '../components/ProfileManager';
  export { ReplayPanel } from '../components/ReplayPanel';
  export { RequestBody } from '../components/RequestBody';
  export { RequestBuilderView } from '../components/RequestBuilderView';
  export { RequestHeaders } from '../components/RequestHeaders';
  export { RequestTemplates } from '../components/RequestTemplates';
  export { SaveToCollection } from '../components/SaveToCollection';
  export { SettingsPanel } from '../components/SettingsPanel';
  export { ShortcutsModal } from '../components/ShortcutsModal';
  export { WorkflowSimulator, WorkflowConfig, WorkflowAssertion, WorkflowStep, WorkflowCondition, WorkflowResult, AssertionResult, LoadTestMetrics } from '../components/WorkflowSimulator';
  export { useKeyboardShortcuts } from '../hooks/useKeyboardShortcuts';
  export { RuntimeVariablesProvider, useRuntimeVariables, interpolateVariables } from '../hooks/useRuntimeVariables';
  export { useTheme, ThemeToggle } from '../hooks/useTheme';
  export { createAIClient, validateApiKey, AIProvider, AIConfig, AIMessage, AIResponse } from '../utils/ai-client';
}
