// Generated by wxt
export {}
declare global {
  const ApiDocGenerator: typeof import('/home/dracon/Dev/extensions/api-debugger/components/ApiDocGenerator').ApiDocGenerator
  const CaptureFilter: typeof import('/home/dracon/Dev/extensions/api-debugger/components/CaptureFilter').CaptureFilter
  const CertificateViewer: typeof import('/home/dracon/Dev/extensions/api-debugger/components/CertificateViewer').CertificateViewer
  const CollectionRunner: typeof import('/home/dracon/Dev/extensions/api-debugger/components/CollectionRunner').CollectionRunner
  const CollectionsView: typeof import('/home/dracon/Dev/extensions/api-debugger/components/CollectionsView').CollectionsView
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const CookieManager: typeof import('/home/dracon/Dev/extensions/api-debugger/components/CookieManager').CookieManager
  const DEFAULT_SHORTCUTS: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useKeyboardShortcuts').DEFAULT_SHORTCUTS
  const DiagnosticsPanel: typeof import('/home/dracon/Dev/extensions/api-debugger/components/DiagnosticsPanel').DiagnosticsPanel
  const EnvironmentManager: typeof import('/home/dracon/Dev/extensions/api-debugger/components/EnvironmentManager').EnvironmentManager
  const ExportPanel: typeof import('/home/dracon/Dev/extensions/api-debugger/components/ExportPanel').ExportPanel
  const GitHubSyncPanel: typeof import('/home/dracon/Dev/extensions/api-debugger/components/GitHubSyncPanel').GitHubSyncPanel
  const ImportExport: typeof import('/home/dracon/Dev/extensions/api-debugger/components/ImportExport').ImportExport
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const MockServerManager: typeof import('/home/dracon/Dev/extensions/api-debugger/components/MockServerManager').MockServerManager
  const ReplayPanel: typeof import('/home/dracon/Dev/extensions/api-debugger/components/ReplayPanel').ReplayPanel
  const RequestBody: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestBody').RequestBody
  const RequestBuilderView: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestBuilderView').RequestBuilderView
  const RequestDetail: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestDetail').RequestDetail
  const RequestHeaders: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestHeaders').RequestHeaders
  const RequestList: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestList').RequestList
  const RequestTemplates: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestTemplates').RequestTemplates
  const RuntimeVariablesProvider: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useRuntimeVariables').RuntimeVariablesProvider
  const SaveToCollection: typeof import('/home/dracon/Dev/extensions/api-debugger/components/SaveToCollection').SaveToCollection
  const SettingsPanel: typeof import('/home/dracon/Dev/extensions/api-debugger/components/SettingsPanel').SettingsPanel
  const ThemeToggle: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useTheme').ThemeToggle
  const apiClient: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').apiClient
  const authFlow: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').authFlow
  const authStore: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').authStore
  const browser: typeof import('wxt/browser').browser
  const config: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').config
  const createAIClient: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/ai-client').createAIClient
  const createFeatureHook: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').createFeatureHook
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defaultMyData: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/store').defaultMyData
  const defaultSettings: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/store').defaultSettings
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const disable: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').disable
  const enable: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').enable
  const executeInActiveTab: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/extension').executeInActiveTab
  const ext: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').ext
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const features: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').default
  const getAllFeatures: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').getAllFeatures
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const getAuthState: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').getAuthState
  const getAvailableModels: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/ai-client').getAvailableModels
  const getExtensionUrl: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/extension').getExtensionUrl
  const getUser: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').getUser
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const interpolateVariables: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useRuntimeVariables').interpolateVariables
  const isAuthenticated: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').isAuthenticated
  const isContentScript: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/extension').isContentScript
  const isEnabled: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').isEnabled
  const isExtensionContext: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/extension').isExtensionContext
  const logout: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').logout
  const myDataStore: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/store').myDataStore
  const openDashboard: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').openDashboard
  const openInNewTab: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/extension').openInNewTab
  const openLogin: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').openLogin
  const resetFeatures: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').resetFeatures
  const sendMessageToActiveTab: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/extension').sendMessageToActiveTab
  const settingsStore: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/store').settingsStore
  const storage: typeof import('wxt/utils/storage').storage
  const subscribe: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').subscribe
  const toggle: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').toggle
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useKeyboardShortcuts: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useKeyboardShortcuts').useKeyboardShortcuts
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useRuntimeVariables: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useRuntimeVariables').useRuntimeVariables
  const useState: typeof import('react').useState
  const useTheme: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useTheme').useTheme
  const validateApiKey: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/ai-client').validateApiKey
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { AIProvider, AIConfig, AIMessage, AIResponse } from '/home/dracon/Dev/extensions/api-debugger/utils/ai-client'
  import('/home/dracon/Dev/extensions/api-debugger/utils/ai-client')
  // @ts-ignore
  export type { DraconConfig, Environment } from '/home/dracon/Dev/extensions/api-debugger/utils/api'
  import('/home/dracon/Dev/extensions/api-debugger/utils/api')
  // @ts-ignore
  export type { MyExtensionSettings, MyDataStore } from '/home/dracon/Dev/extensions/api-debugger/utils/store'
  import('/home/dracon/Dev/extensions/api-debugger/utils/store')
}
