// Generated by wxt
export {}
declare global {
  const ApiDocGenerator: typeof import('/home/dracon/Dev/extensions/api-debugger/components/ApiDocGenerator').ApiDocGenerator
  const CaptureFilter: typeof import('/home/dracon/Dev/extensions/api-debugger/components/CaptureFilter').CaptureFilter
  const CertificateViewer: typeof import('/home/dracon/Dev/extensions/api-debugger/components/CertificateViewer').CertificateViewer
  const CollectionRunner: typeof import('/home/dracon/Dev/extensions/api-debugger/components/CollectionRunner').CollectionRunner
  const CollectionsView: typeof import('/home/dracon/Dev/extensions/api-debugger/components/CollectionsView').CollectionsView
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const CookieManager: typeof import('/home/dracon/Dev/extensions/api-debugger/components/CookieManager').CookieManager
  const DiagnosticsPanel: typeof import('/home/dracon/Dev/extensions/api-debugger/components/DiagnosticsPanel').DiagnosticsPanel
  const EnvironmentManager: typeof import('/home/dracon/Dev/extensions/api-debugger/components/EnvironmentManager').EnvironmentManager
  const ExportPanel: typeof import('/home/dracon/Dev/extensions/api-debugger/components/ExportPanel').ExportPanel
  const GettingStarted: typeof import('/home/dracon/Dev/extensions/api-debugger/components/GettingStarted').GettingStarted
  const GitHubSyncPanel: typeof import('/home/dracon/Dev/extensions/api-debugger/components/GitHubSyncPanel').GitHubSyncPanel
  const ImportExport: typeof import('/home/dracon/Dev/extensions/api-debugger/components/ImportExport').ImportExport
  const ImportModal: typeof import('/home/dracon/Dev/extensions/api-debugger/components/ImportModal').ImportModal
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const MockServerManager: typeof import('/home/dracon/Dev/extensions/api-debugger/components/MockServerManager').MockServerManager
  const ProfileManager: typeof import('/home/dracon/Dev/extensions/api-debugger/components/ProfileManager').ProfileManager
  const ReplayPanel: typeof import('/home/dracon/Dev/extensions/api-debugger/components/ReplayPanel').ReplayPanel
  const RequestBody: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestBody').RequestBody
  const RequestBuilderView: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestBuilderView').RequestBuilderView
  const RequestDetail: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestDetail').RequestDetail
  const RequestHeaders: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestHeaders').RequestHeaders
  const RequestList: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestList').RequestList
  const RequestTemplates: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestTemplates').RequestTemplates
  const RuntimeVariablesProvider: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useRuntimeVariables').RuntimeVariablesProvider
  const SAMPLE_COLLECTIONS: typeof import('/home/dracon/Dev/extensions/api-debugger/components/WelcomeScreen').SAMPLE_COLLECTIONS
  const SaveToCollection: typeof import('/home/dracon/Dev/extensions/api-debugger/components/SaveToCollection').SaveToCollection
  const SettingsPanel: typeof import('/home/dracon/Dev/extensions/api-debugger/components/SettingsPanel').SettingsPanel
  const ShortcutsModal: typeof import('/home/dracon/Dev/extensions/api-debugger/components/ShortcutsModal').ShortcutsModal
  const TestMode: typeof import('/home/dracon/Dev/extensions/api-debugger/components/TestMode').TestMode
  const ThemeToggle: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useTheme').ThemeToggle
  const WelcomeScreen: typeof import('/home/dracon/Dev/extensions/api-debugger/components/WelcomeScreen').WelcomeScreen
  const WorkflowSimulator: typeof import('/home/dracon/Dev/extensions/api-debugger/components/WorkflowSimulator').WorkflowSimulator
  const browser: typeof import('wxt/browser').browser
  const createAIClient: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/ai-client').createAIClient
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const interpolateVariables: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useRuntimeVariables').interpolateVariables
  const storage: typeof import('wxt/utils/storage').storage
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useKeyboardShortcuts: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useKeyboardShortcuts').useKeyboardShortcuts
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useRuntimeVariables: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useRuntimeVariables').useRuntimeVariables
  const useState: typeof import('react').useState
  const useTheme: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useTheme').useTheme
  const validateApiKey: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/ai-client').validateApiKey
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { WorkflowConfig, WorkflowAssertion, WorkflowStep, WorkflowCondition, WorkflowResult, AssertionResult, LoadTestMetrics } from '/home/dracon/Dev/extensions/api-debugger/components/WorkflowSimulator'
  import('/home/dracon/Dev/extensions/api-debugger/components/WorkflowSimulator')
  // @ts-ignore
  export type { AIProvider, AIConfig, AIMessage, AIResponse } from '/home/dracon/Dev/extensions/api-debugger/utils/ai-client'
  import('/home/dracon/Dev/extensions/api-debugger/utils/ai-client')
}
