// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { getAppConfig, useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { useState, useCallback, useMemo, useEffect, useRef, useContext, useReducer } from 'react';
  export { fakeBrowser } from 'wxt/testing';
  export { CaptureFilter } from '../components/CaptureFilter';
  export { CollectionsView } from '../components/CollectionsView';
  export { CookieManager } from '../components/CookieManager';
  export { DiagnosticsPanel } from '../components/DiagnosticsPanel';
  export { EnvironmentManager } from '../components/EnvironmentManager';
  export { ExportPanel } from '../components/ExportPanel';
  export { ImportExport } from '../components/ImportExport';
  export { ReplayPanel } from '../components/ReplayPanel';
  export { RequestBody } from '../components/RequestBody';
  export { RequestBuilderView } from '../components/RequestBuilderView';
  export { RequestDetail } from '../components/RequestDetail';
  export { RequestHeaders } from '../components/RequestHeaders';
  export { RequestList } from '../components/RequestList';
  export { SaveToCollection } from '../components/SaveToCollection';
  export { SettingsPanel } from '../components/SettingsPanel';
  export { useKeyboardShortcuts, DEFAULT_SHORTCUTS } from '../hooks/useKeyboardShortcuts';
  export { RuntimeVariablesProvider, useRuntimeVariables, interpolateVariables } from '../hooks/useRuntimeVariables';
  export { useTheme, ThemeToggle } from '../hooks/useTheme';
  export { createAIClient, getAvailableModels, validateApiKey, AIProvider, AIConfig, AIMessage, AIResponse } from '../utils/ai-client';
  export { ext, config, apiClient, authFlow, authStore, getAuthState, isAuthenticated, openLogin, openDashboard, logout, getUser, subscribe, DraconConfig, Environment } from '../utils/api';
  export { isContentScript, isExtensionContext, getExtensionUrl, sendMessageToActiveTab, executeInActiveTab, openInNewTab } from '../utils/extension';
  export { default as features, isEnabled, enable, disable, toggle, getAllFeatures, resetFeatures, createFeatureHook } from '../utils/features';
  export { defaultSettings, settingsStore, defaultMyData, myDataStore, MyExtensionSettings, MyDataStore } from '../utils/store';
}
