// Generated by wxt
export {}
declare global {
  const CollectionsView: typeof import('/home/dracon/Dev/extensions/api-debugger/components/CollectionsView').CollectionsView
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const DiagnosticsPanel: typeof import('/home/dracon/Dev/extensions/api-debugger/components/DiagnosticsPanel').DiagnosticsPanel
  const ExportPanel: typeof import('/home/dracon/Dev/extensions/api-debugger/components/ExportPanel').ExportPanel
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const ReplayPanel: typeof import('/home/dracon/Dev/extensions/api-debugger/components/ReplayPanel').ReplayPanel
  const RequestBody: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestBody').RequestBody
  const RequestDetail: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestDetail').RequestDetail
  const RequestHeaders: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestHeaders').RequestHeaders
  const RequestList: typeof import('/home/dracon/Dev/extensions/api-debugger/components/RequestList').RequestList
  const action: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/analytics').action
  const analytics: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/analytics').default
  const apiClient: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').apiClient
  const authFlow: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').authFlow
  const authStore: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').authStore
  const browser: typeof import('wxt/browser').browser
  const clearQueue: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/analytics').clearQueue
  const config: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').config
  const createFeatureHook: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').createFeatureHook
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const createWasmRateLimiter: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/wasm-demo').createWasmRateLimiter
  const debug: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/debug').default
  const defaultMyData: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/store').defaultMyData
  const defaultSettings: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/store').defaultSettings
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const demoExtractFromMarkdown: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/wasm-demo').demoExtractFromMarkdown
  const demoExtractJson: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/wasm-demo').demoExtractJson
  const demoValidateEmail: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/wasm-demo').demoValidateEmail
  const disable: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').disable
  const enable: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').enable
  const error: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/debug').error
  const executeInActiveTab: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/extension').executeInActiveTab
  const ext: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').ext
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const features: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').default
  const getAllFeatures: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').getAllFeatures
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const getAuthState: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').getAuthState
  const getDebugInfo: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/debug').getDebugInfo
  const getExtensionUrl: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/extension').getExtensionUrl
  const getQueuedEvents: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/analytics').getQueuedEvents
  const getUser: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').getUser
  const initWasm: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/wasm-demo').initWasm
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isAuthenticated: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').isAuthenticated
  const isContentScript: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/extension').isContentScript
  const isEnabled: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').isEnabled
  const isExtensionContext: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/extension').isExtensionContext
  const isWasmReady: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/wasm-demo').isWasmReady
  const log: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/debug').log
  const logout: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').logout
  const measure: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/debug').measure
  const measureAsync: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/debug').measureAsync
  const mockResponse: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/debug').mockResponse
  const myDataStore: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/store').myDataStore
  const openDashboard: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').openDashboard
  const openInNewTab: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/extension').openInNewTab
  const openLogin: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').openLogin
  const pageView: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/analytics').pageView
  const resetFeatures: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').resetFeatures
  const sendMessageToActiveTab: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/extension').sendMessageToActiveTab
  const settingsStore: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/store').settingsStore
  const simulateDelay: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/debug').simulateDelay
  const storage: typeof import('wxt/utils/storage').storage
  const subscribe: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/api').subscribe
  const toggle: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/features').toggle
  const track: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/analytics').track
  const trackError: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/analytics').trackError
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useAsync: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useAsync').default
  const useAuth: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useAuth').default
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useStorage: typeof import('/home/dracon/Dev/extensions/api-debugger/hooks/useStorage').default
  const warn: typeof import('/home/dracon/Dev/extensions/api-debugger/utils/debug').warn
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { AnalyticsEvent } from '/home/dracon/Dev/extensions/api-debugger/utils/analytics'
  import('/home/dracon/Dev/extensions/api-debugger/utils/analytics')
  // @ts-ignore
  export type { DraconConfig, Environment } from '/home/dracon/Dev/extensions/api-debugger/utils/api'
  import('/home/dracon/Dev/extensions/api-debugger/utils/api')
  // @ts-ignore
  export type { DebugInfo } from '/home/dracon/Dev/extensions/api-debugger/utils/debug'
  import('/home/dracon/Dev/extensions/api-debugger/utils/debug')
  // @ts-ignore
  export type { MyExtensionSettings, MyDataStore } from '/home/dracon/Dev/extensions/api-debugger/utils/store'
  import('/home/dracon/Dev/extensions/api-debugger/utils/store')
}
