// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/_locales/en/messages.json"
    | "/auth-callback.html"
    | "/background.js"
    | "/popup.html"
    | "/wasm/dracon_wasm.d.ts"
    | "/wasm/dracon_wasm.js"
    | "/wasm/dracon_wasm_bg.wasm"
    | "/wasm/dracon_wasm_bg.wasm.d.ts"
    | "/wasm/package.json"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
